---
includes: []
files: [src/bfsp.proto src/bfsp.ipc.proto src/bfsp.cli.proto src/bfsp.internal.proto]
output: src/
messages:
  - paths: []
    attrs:
      - derive(serde::Serialize, serde::Deserialize, validator::Validate)
      - serde(default)
enums:
  - paths: []
    attrs:
      - derive(serde::Serialize, serde::Deserialize, validator::Validate)
      - serde(rename_all = "lowercase")
fields:
  - paths: []
    attrs:
      - validate(email)
btree_map: ['.']
bytes: ['.']
